def base_counter(string):
    a = string.count("A")
    c = string.count("C")
    g = string.count("G")
    t = string.count("T")
    result = str(a) + " " + str(c) + " " + str(g) + " " + str(t) 
    return result 
       
string = "TGGGAATGCTTCCTGATGGATTATAACCCGTGTTGATATGACCTGCGTCGTCGGGTTACTCCTCAAATTAACTATTTTCCCCCATGCATACATTTGAAGCATCTAATAAATTATCCATTTCGCATACCCGCCGCACCCCCCGCTACCTAGAAAACACACCGCAATTCCTACCGGTAGTCCGTCGACTGTAAGAGCGACAGGGCAGCTCGCGACTAACGATTCTCATGCGCTCGCCCAGGCTTAGTCCCCATGTTAAGGTAAACGTTAGGATGGCTCATGGCGACCGCCACGTTTGAAACTGGTAAGGTAGAATACGCGCAGTCATAGGTATTGGAGCAGGATTGACGGGACCTCAGCGCCCCTGCTTGAGGCCAGATACGCAGGGGCAATAGTCACTGTAGACATAACCAAATAAGGAGCTTTCGACCAGTCAGTCCTCATAGACTTTTGTCGCATCAGGTAGCGACTCGTCAACATTCTATATCGAAACTTTGGTTCGGACAGTACTTGACGGCATTGAATCCGCCAAGTGGAACTGAGGCACATGGCGCCATCCGCCTGTACGGAAGAGTCGGACATCTGAATTCCAGCTATCCAGCACCGGGGAGAGCGCCATCCCGTTACGTGCCGCATACGACGGTAAACTCACCATTAGGCATAACAGGATGCGACCCATTACGTGTTTGAGCAGAGGCAGCTACTCAGAACTGGTGAGTAGTTCAGAACGCCGCGGAAAGTCCCCAGAATGAAAAGCTAGCCAGCTCTGTGTTAGAAATGGAAGTTCATCCAAAACCGTACACGGGCATTCAGTTTCCGAATACGGCCCGCTGGCCGTAATTTTAATTTAGAATCGGTAACGCACGCATTTTTTCGCAGTGTGCTGGAGTTATAATCG"
print(base_counter(string))