def complementing_dna(string):
    #result = string.replace(("A", "T"), ("T", "A"))
    #result = string.replace(("C", "G"), ("G", "C"))
    #result = string.replace("G", "C") 
    #result = string.replace("T", "A")
    r_string= string[::-1]
    
    result = " " 
    for char in r_string:
        if char == "A":
            result += "T"
        elif char == "T":
            result += "A"
        elif char == "C":
            result += "G"
        elif char == "G":
            result += "C"
    return result 
    


string="CTAGTCCACCTCGATTGAGACCACAAGCTGTGATGCGGTAACACATTCATAATACACCTTATTGGCTTAGAGGCAAAGATTGCCCTATGGTGACCACTCGGAAGCGCAATCCCACTGTTGGAGGACGGGGCCTTGAGCCTGTCTCTTACCCGTCGTGACCAGGGTACGGAAACTTAGGCTGGTACTCTATCATGGGGAACATAAGCCCCATTGTATCGGCCCTAGCTGGTTATTGCAATCCGCTTGCTTCGGTCATCGTGCCACCTTTTCGGTATTCACCTGTGATAGGAACCTGAGCCATACAGGTCCAACGACAATGCCGAGTGCGGCGTACAAAAGAGACAATCGATTTTTTAAGGTGGGGTCCACACGTAATGCGACGGTATAACCAACGTTCCGAAGGGTCTGCGTCGCCCCGTTAGAAATATTCAATGACCAGGTCGACTCCAAAGCCAAAACAGCCGTTCATAGCGGGCTAAGATTTAGCTCACTCAGCTGGTGTTGTGATGCGTAGATTCCGTCGCTCCATACAGCGACCTCGCTATATAGCTAGGCTGGCTCGTGACGTTATCACGTTGATTGATTACAGCTCACAGAGCGAGAGCCAACTGCCGTAGCTGTTACCCTGGCACGTTCGAAGTTGCACTCAAGTGTAATATCCCTAGCGAGAATAGGCAAAGTGGATAAAAGGTTAGCGGGATGAGATTGACAGGCATGCAATGCGGGGTTACTCCTGAGTCATCGTCACTAATGGGTCTAATTGTACTGCAACTCCCCTGGGAGCTCGTGACCCGTCTTCCATGTGAGGGCGTATATGCCAAATATGCAGGAGTTGTCTTAGGAAGACGTTCTGTTCGTTTTATCGGGAAAGTATGTTTGTCACCAGTCGGTCTGAGCCCAGATCTAGGCCAACGGCGTGCTACATAGAACGATGCCTCCCCCCAATACAT"
print(complementing_dna(string))