#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 18 10:16:52 2019

@author: carlottaceccacci
"""
s = "TCCGTTTACTCGCCGTTTATCCGTTTATCCCGTTTACCGCCGTTTATCGCCGTTTATCCGTTTACCGTTTACCGTTTAGGAAAGAGCCGGGATCCGTTTAGCCGTTTAGGTCCTAGCCGTTTACCCGTTTAGCCGTTTACCGTTTACCGTTTACACGATCTTCGCCGTTTAATTAGGGCCTCGATAGGTTTTTATCCGTTTACCGTTTAATAACCGTTTAGAGGGTCCGTTTAGCTCCGTTTACCGTTTACCGTTTACTGACCGTTTAGACCGTTTACCGTTTACCCGTTTAGTTGTGCCGTTTAGGCTCCCGTTTACCGTTTACCCGTTTACGCCGTTTAAGACCGTTTAGGTACCGTTTATCCGTTTAGCCCCGTTTAAGGATCATCCGTTTACCGTTTACCTGGTCCGTTTAACCGTTTAAACACCCCGTTTACCCGTTTACCGTTTACCGTTTACTCTTTCCGTTTAGACCGTTTACCGTTTAAGAAGAACCGTCCGTTTACCGTTTAACCGTTTACCGTTTAAGCGCCGTTTATTGACCGTTTACACAAGCCGTTTATCCGTTTAGGTGTCCGTTTAGCCGTTTAAGCGACCGTTTATTCCGTTTAGGGAAATGCCGTTTAACATGTTCCGTTTACCGTTTAGTCCGTTTACCGTTTATGTACTAAACCGTTTACACCGTTTACCGTTTACGCCGTTTAAATCCGTTTACCGTTTATTCCGTTTACACCGTGGCCCGTTTACCGTTTAGGACCCGTTTACCGTTTACGATGTACCCGTTTACACACCGTTTACACCGCCGTTTAGGCCGTTTA"
t =  "CCGTTTACC"
def subs(s,t):
    l = []
    for i in range (0, len(s) - len(t)):
        a = s [i:i + len(t)]
        if (a == t):
            l.append(i+1)
            
            
    return l 

print(*subs(s,t))
    